### PR TITLE
Code for initial release

### PR DESCRIPTION
**Pull request by adamshaylor**
This is mostly the same as lobelia-earth/lobelia-explore#86. I whipped together a quick, mostly trivial test to make sure the exports and source maps worked. They didn’t, partly because I was trying to get fancy by building both minified and un-minified outputs, which is probably not worthwhile since we’re including the source with the package. Anyway, those are fixed now and this is what the test looks like.

https://github.com/user-attachments/assets/110735ec-d475-4122-85d6-2d5483d8359f

I can share the source for this test if anyone is curious, but the principle should be the same regardless of whether the state container is Pinia, Redux, or a map engine. So long as you can pass in a well-typed default state object and replace the current state with an object of the same shape, you can use this library.

I closed the other PR before anyone really had a chance to fully review it. Feedback is welcome, especially since I haven’t released this yet. If you have any concerns—especially about the architecture and API design—it will be easier to address those now than after we release.

### CODE REVIEW

**Comment by adamshaylor** [comment]
I see the build failure. That’s my faulty Github Actions setup. Working on it...

**Comment by adamshaylor** [comment]
...fixed.

**Review by paumoreno — APPROVED** [review]
Thank you for implementing this! It feels very natural to work with, and the fact that it's strongly typed makes using it super comfortable. Already looking forward to use it in a real scenario!

**Comment by adamshaylor** [comment]
I think we’ve all been a bit busy with project work over the last month, but I am coming back to this today. Unless anyone has any objections, I will merge and release this afternoon. I’m also adding @vallode, who I think was moving when I initially opened this, in case he has any feedback.

**Pull request merged**
